### PR TITLE
Docker image

### PR DESCRIPTION
**Pull request by gdunstone**
This pull request adds a Dockerfile so that you can build a docker image for it.

It builds fine with the automated builds with Dockerhub if you want to set that up.

I did an automated build here: https://hub.docker.com/r/gdunstone/iview-proxy

### CODE REVIEW

**Comment by gdunstone** [comment]
If you want to setup automated builds from your fork then Ill delete my docker hub repo.

**Comment by king-millez** [comment]
Just tested this - working fine obviously. Maybe just add the necessary commands to the README, then I'll merge.

**Comment by gdunstone** [comment]
Just pushed a readme for the docker image.

If you create an account on dockerhub for OpenGovAus then you can have automated builds on commits to the main fork.

**Comment by gdunstone** [comment]
@king-millez Can you merge this?

**Pull request merged**
